### ISSUE TITLE
Register Village with CCC organizers

### ISSUE THREAD

**Issue by jhilden** [opencodetown/Chaos-Communication-Camp-2015#6]
The wiki for villages is online now:  https://events.ccc.de/camp/2015/wiki/Static:Villages

Once we have figured out who/what exactly our village will be, we should register it.

We should also think about renting a tent:  https://events.ccc.de/camp/2015/wiki/Rent_a_Tent  What size would make sense?

**Comment by finnp** [comment]
Since we seem to have settled for "Open Code Town" we could do this now.

We have to do this until June 20th.  However there's a big lists of things that we have to tell the organizers, including how big our village will be, what kind of internet and power we want etc. 

Maybe we can have a hangout (or another IRL meeting in Berlin) and do this together?

**Comment by Lelith** [comment]
+1 on hangout / irl meeting in berlin. 
we should also add a deadline in the "who wants to join the village" list. because if we plan now for e.g. 20 people but in the end are 35 it will not work out.

**Comment by sangyye** [comment]
+1 on the hangout (irl meeting in berlin not possible for me)

(can we maybe consider https://beta.talky.io/ instead of hangouts? Would not need a google account, which some people don't have or don't want)

**Comment by finnp** [comment]
Here it is: http://events.ccc.de/camp/2015/wiki/Village:OpenCodeTown
